name: retic_demo
channels:
- conda-forge
dependencies:
- python=3.10,
- ipython
- jupyterlab
- loguru
- matplotlib-base
- nsight-compute
- numpy
- pandas
- pytest
- python-dotenv
- ruff
- scikit-learn
- tqdm
- typer
